# Generated by Django 6.0.1 on 2026-02-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('manager', 'Manager'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
