# Generated by Django 6.0.1 on 2026-03-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_deleted_at_order_is_deleted_orderitem_product'),
        ('shop', '0003_alter_productimage_options_productimage_created_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='orders_orde_product_32ff41_idx'),
        ),
    ]
