# Generated by Django 6.0.1 on 2026-03-01 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_status', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatushistory',
            options={'ordering': ['-timestamp']},
        ),
    ]
