# Generated by Django 6.0.1 on 2026-03-23 13:51

import apps.shop.models
import config.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productimage_options_productimage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=config.storage.MediaStorage(), upload_to='products/%Y/%m/', validators=[apps.shop.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=config.storage.MediaStorage(), upload_to='products/thumbnails/%Y/%m/'),
        ),
    ]
