# Generated by Django 6.0.1 on 2026-05-16 00:02

import apps.shop.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='C:\\project\\shop\\backend\\media'), upload_to='products/%Y/%m/', validators=[apps.shop.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='C:\\project\\shop\\backend\\media'), upload_to='products/thumbnails/%Y/%m/'),
        ),
    ]
