# Generated by Django 6.0.1 on 2026-02-14 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
        ('payments', '0002_remove_paymenttransaction_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='order',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='status',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='idempotency_key',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='provider_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='raw_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('paypal', 'PayPal'), ('card', 'Card'), ('crypto', 'Crypto')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.payment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='payments.payment'),
        ),
    ]
